### ISSUE TITLE
Set expiry on cloudwatch logs & general cleanup

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/infrastructure-provisioning#7]
Need to set the expiry on all cloudwatch logs. I have so far updated `circles-backend-rocketchat` `circles-backend-rocketchat-ecs` and `circles-backend-webservices`

Need to do similar on for the blockchain stuff: issue here: https://github.com/CirclesUBI/blockchain-provisioning/issues/7

**Comment by edzillion** [comment]
I have added 
```
  deployment_maximum_percent         = "100"
  deployment_minimum_healthy_percent = "50"
```
to rocketchat's ECS service, which should allow automated blue-green deployments. i.e. we have 2 rocketchat instances, this will allow each one to be shutdown automatically and replaced.

**Comment by xwvvvvwx** [comment]
Can we close this issue if it's in the Done column on the board?

**Comment by edzillion** [comment]
sure
